name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Setup Node.js (to build the project)
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Use the version of Node.js your project requires

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the project (adjust based on your build command)
      - name: Build project
        run: npm run build  # Change to your build command, e.g., `npm run build` for a Vite app

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Ensure this matches your build output directory (e.g., Vite's `dist`)
